# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fac911ef0f39842b6c67a92bcca33fd607d5213e50be87972e5f4fb83513341e5266018455b4485e276ade330e908addcdb7b0ee9d9b948eac1f0c78b14dd99

test:
  secret_key_base: 5ccece848daac9cce80b3dcf10fa2892970b0062eeb6c941728a2439e1b3583da209b1ea3671b123bb2034a574b2ec16d3759ea5598672fe8836715dd7e1a92c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
